-- ตารางสินค้า
CREATE TABLE IF NOT EXISTS products (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title       TEXT           NOT NULL CHECK (length(trim(title)) > 0),
  price       NUMERIC(10, 2) NOT NULL CHECK (price >= 0),
  stock       INTEGER        NOT NULL CHECK (stock >= 0),
  category    TEXT           NOT NULL,
  description TEXT,
  thumbnail   TEXT
);
