-- ข้อมูลสินค้า 30 รายการ ส่งออกเมื่อ 2026-10-04T10:07:39.539Z
-- สร้างด้วย npm run db:export และถูกนำเข้าอัตโนมัติโดย npm run db:start / db:setup
INSERT INTO products (id, title, price, stock, category, description, thumbnail) VALUES
  (1, 'Essence Mascara Lash Princess', 9.99, 5, 'beauty', NULL, 'https://cdn.dummyjson.com/product-images/beauty/essence-mascara-lash-princess/thumbnail.webp'),
  (2, 'Eyeshadow Palette with Mirror', 19.99, 44, 'beauty', NULL, 'https://cdn.dummyjson.com/product-images/beauty/eyeshadow-palette-with-mirror/thumbnail.webp'),
  (5, 'Red Lipstick', 12.99, 34, 'beauty', NULL, 'https://cdn.dummyjson.com/product-images/beauty/red-lipstick/thumbnail.webp'),
  (11, 'Annibale Colombo Bed', 1899.99, 74, 'furniture', NULL, 'https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-bed/thumbnail.webp'),
  (12, 'Annibale Colombo Sofa', 2499.99, 91, 'furniture', NULL, 'https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-sofa/thumbnail.webp'),
  (13, 'Bedside Table African Cherry', 299.99, 88, 'furniture', NULL, 'https://cdn.dummyjson.com/product-images/furniture/bedside-table-african-cherry/thumbnail.webp'),
  (19, 'Apple Watch Series 8', 599.99, 20, 'mobile-accessories', NULL, NULL),
  (20, 'Beats Flex Wireless Earphones', 49.99, 79, 'mobile-accessories', NULL, 'https://cdn.dummyjson.com/product-images/mobile-accessories/beats-flex-wireless-earphones/thumbnail.webp'),
  (22, 'Beats Studio Buds', 179.99, 74, 'mobile-accessories', NULL, NULL),
  (32, 'Apple Magic Mouse', 99.99, 34, 'mobile-accessories', NULL, NULL),
  (41, 'Vanilla Essential Oil', 11.99, 33, 'fragrances', NULL, NULL),
  (45, 'Dior J''adore', 89.99, 79, 'fragrances', NULL, 'https://cdn.dummyjson.com/product-images/fragrances/dior-j''adore/thumbnail.webp'),
  (50, 'Al Munakh by Al Haramain', 8.99, 79, 'fragrances', NULL, NULL),
  (63, 'Apple', 1.99, 32, 'groceries', NULL, 'https://cdn.dummyjson.com/product-images/groceries/apple/thumbnail.webp'),
  (65, 'Beef Steak', 12.99, 96, 'groceries', NULL, 'https://cdn.dummyjson.com/product-images/groceries/beef-steak/thumbnail.webp'),
  (70, 'Cooking Oil', 4.99, 87, 'groceries', NULL, 'https://cdn.dummyjson.com/product-images/groceries/cooking-oil/thumbnail.webp'),
  (76, 'Green Chili Pepper', 0.99, 44, 'groceries', NULL, 'https://cdn.dummyjson.com/product-images/groceries/green-chili-pepper/thumbnail.webp'),
  (89, 'Handcrafted Wood Mirror', 379.99, 40, 'home-decoration', NULL, NULL),
  (90, 'Handcrafted Wooden Cabinet', 399.99, 21, 'home-decoration', NULL, NULL),
  (98, 'Vintage Rustic Wall Decoration', 39.99, 25, 'home-decoration', NULL, NULL),
  (104, 'Table Lamp', 79.99, 30, 'kitchen-accessories', NULL, 'https://cdn.dummyjson.com/product-images/home-decoration/table-lamp/thumbnail.webp'),
  (108, 'Plant Hanger For Home', 41.90, 65, 'kitchen-accessories', NULL, NULL),
  (117, 'Apple MacBook Pro 14 Inch Space Grey', 1999.99, 47, 'laptops', NULL, 'https://cdn.dummyjson.com/product-images/laptops/apple-macbook-pro-14-inch-space-grey/thumbnail.webp'),
  (119, 'Asus Zenbook Pro Dual Screen Laptop', 1899.99, 34, 'laptops', NULL, 'https://cdn.dummyjson.com/product-images/laptops/asus-zenbook-pro-dual-screen-laptop/thumbnail.webp'),
  (121, 'HP Pavilion 15-DK1056WM', 1099.99, 68, 'laptops', NULL, NULL),
  (126, 'Gucci Bag', 1249.99, 29, 'womens-bags', NULL, NULL),
  (131, 'Louis Vuitton Bag', 1500.00, 60, 'womens-bags', NULL, NULL),
  (141, 'Puma Perfect Fit T-shirt', 27.99, 46, 'tops', NULL, NULL),
  (153, 'Aviator Sunglasses', 25.99, 78, 'sunglasses', NULL, NULL),
  (165, 'Amazon Echo Plus', 99.99, 25, 'smartphones', NULL, 'https://cdn.dummyjson.com/product-images/mobile-accessories/amazon-echo-plus/thumbnail.webp');
SELECT setval(pg_get_serial_sequence('products', 'id'), COALESCE((SELECT MAX(id) FROM products), 1));
